#### general settings
name: STTrans2_scratch
use_tb_logger: false #true
model: VideoSR_base
distortion: sr
scale: 4
gpu_ids: [2, 3]


#### datasets
datasets:
  train:
    name: Vimeo7
    mode: Vimeo7
    interval_list: [1]
    random_reverse: true #false
    border_mode: false
    dataroot_GT: /media/DATA2/wzr/vimeo_septuplet/vimeo7_train_GT.lmdb
    dataroot_LQ: /media/DATA2/wzr/vimeo_septuplet/vimeo7_train_LR7.lmdb

    cache_keys: Vimeo7_train_keys.pkl 

    N_frames: 7
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 6
    GT_size: 128
    LQ_size: 32
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
network_G:
  which_model_G: STTrans2
  nf: 64
  nframes: 7
  embed_dim: 72
  HR_in: false

#### path
path:
  pretrain_model_G: ~ 
  strict_load: true #true #
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-5
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1 #4000  # -1: no warm up
  T_period: [150000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 1e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
